package com.example.examinationcardgame

enum class Card (val resourceId: Int){

    CARD_BACKGROUND(R.drawable.background_card),

    CLUBS_1(R.drawable.clubs1),
    CLUBS_2(R.drawable.clubs2),
    CLUBS_3(R.drawable.clubs3),
    CLUBS_4(R.drawable.clubs4special),
    CLUBS_5(R.drawable.clubs5),
    CLUBS_6(R.drawable.clubs6),
    CLUBS_7(R.drawable.clubs7),
    CLUBS_8(R.drawable.clubs8),
    CLUBS_9(R.drawable.clubs9),
    CLUBS_JACKDEATH(R.drawable.clubsjackdeath),
    CLUBS_JACKSAVED(R.drawable.clubsjacksaved),
    CLUBS_JACKSURVIVE(R.drawable.clubsjacksurvive),
    CLUBS_QUEEN(R.drawable.clubsqueen),
    CLUBS_KING(R.drawable.clubsking),
    CLUBS_ACE(R.drawable.clubsace),

    SPADES_1(R.drawable.spades1),
    SPADES_2(R.drawable.spades2),
    SPADES_3(R.drawable.spades3),
    SPADES_4(R.drawable.spades4),
    SPADES_5(R.drawable.spades5),
    SPADES_6(R.drawable.spades6),
    SPADES_7(R.drawable.spades7),
    SPADES_8(R.drawable.spades8),
    SPADES_9(R.drawable.spades9),
    SPADES_JACK(R.drawable.spadesjack),
    SPADES_QUEEN(R.drawable.spadesqueen),
    SPADES_KING(R.drawable.spadeskingspecial),
    SPADES_ACE(R.drawable.spadesace),

    HEARTS_1(R.drawable.hearts1),
    HEARTS_2(R.drawable.hearts2),
    HEARTS_3(R.drawable.hearts3),
    HEARTS_4(R.drawable.hearts4),
    HEARTS_5(R.drawable.hearts5),
    HEARTS_6(R.drawable.hearts6),
    HEARTS_7(R.drawable.hearts7),
    HEARTS_8(R.drawable.hearts8),
    HEARTS_9(R.drawable.hearts9),
    HEARTS_JACK(R.drawable.heartsjack),
    HEARTS_QUEEN(R.drawable.heartsqueen),
    HEARTS_KING(R.drawable.heartsking),
    HEARTS_ACE(R.drawable.heartsace),
}